Issue 36 cases tags
EthicApp-Development/casevault-main pull request #43
Opened 2024-05-30 06:23 UTC by sofiagadea

Etiquetas agregados a casos que servirán para el buscador, se pueden crear nuevas etiquetas o utilizar las existentes. 
![Captura desde 2024-05-30 02-15-35](https://github.com/EthicApp-Development/casevault-main/assets/80332639/bb4e7b9c-6143-4c37-8148-3d9c1fd98754)
[Grabación de pantalla desde 30-05-24 02:21:21.webm](https://github.com/EthicApp-Development/casevault-main/assets/80332639/57c4d84c-523b-4098-b212-33a7313d23d5)

2024-05-30 13:35 UTC, claudio-alvarez requested changes
Me ha gustado el despliegue de tags y la función de tagging. Sin embargo, por un tema de prioridad de contenido, creo que quedaría mejor si ubicamos el tagging debajo del título del caso y antes de la descripción. Cuidemos que se vea bien el layout con márgenes superior-inferior adecuados entre los elementos de form.

Además, ojo que el label del formulario de tags difiere en estilo al resto de los campos de texto.

2024-06-04 15:16 UTC, sofiagadea reviewed
Cambios realizados

2024-06-06 13:50 UTC, claudio-alvarez approved these changes

2024-06-06 13:51 UTC, claudio-alvarez approved these changes

2024-06-06 14:01 UTC, claudio-alvarez approved these changes
Está la funcionalidad necesaria, pero ojo con la seguridad:

- Eliminación indiscriminada de tags.
- Creación indiscriminada de tags.

Lo primero se resolvería con un control de acceso implementado. Lo segundo requiere una solución de "rate limiting", que podría usarse en conjunto con un WAF.

Dejo esta conversación con GPT con referencias al respecto:

https://chatgpt.com/share/528fc0e3-b18d-4892-8937-a9ffc9cf3dfc

Estimo que tendremos que crear issues para implementar lo del rate limiting, pues el control de acceso sí lo tenemos considerado.

2024-06-06 14:02 UTC, jorgeplazadelosreyes approved these changes

2024-06-06 14:02 UTC, claudio-alvarez approved these changes

2024-06-06 14:03 UTC, merged